name: GitHub Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: "${{ secrets.RELEASE_KEY }}"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - run: |
          python -m pip install build
          python -m build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
          body: ${{ github.event.head_commit.message }}
